/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monorailbookingsystem;

/**
 *
 * @author ahmedsherif
 */
public class AdminMenu extends javax.swing.JFrame {
    private  Admin A= new Admin();

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }
    public AdminMenu(Admin a){
        initComponents();
        A=a;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddTrain = new javax.swing.JButton();
        Head = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        EditAccount = new javax.swing.JButton();
        RemoveTrain = new javax.swing.JButton();
        UpdateTrain = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        GenerateReport1 = new javax.swing.JButton();
        GenerateReport2 = new javax.swing.JButton();

        AddTrain.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        AddTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        AddTrain.setText("Add Train");
        AddTrain.setBorderPainted(false);
        AddTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrainActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Head.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Head.setText("Admin Menu");
        getContentPane().add(Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditAccount.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        EditAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        EditAccount.setText("Edit Account");
        EditAccount.setBorderPainted(false);
        EditAccount.setContentAreaFilled(false);
        EditAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAccountActionPerformed(evt);
            }
        });
        Background.add(EditAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        RemoveTrain.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        RemoveTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        RemoveTrain.setText("Remove Train");
        RemoveTrain.setBorderPainted(false);
        RemoveTrain.setContentAreaFilled(false);
        RemoveTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTrainActionPerformed(evt);
            }
        });
        Background.add(RemoveTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        UpdateTrain.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        UpdateTrain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        UpdateTrain.setText("Update Train");
        UpdateTrain.setBorderPainted(false);
        UpdateTrain.setContentAreaFilled(false);
        UpdateTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTrainActionPerformed(evt);
            }
        });
        Background.add(UpdateTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/monorail.png"))); // NOI18N
        Background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 178, -1, 130));

        text.setFont(new java.awt.Font("Noteworthy", 0, 24)); // NOI18N
        text.setText("Monorail System");
        Background.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        GenerateReport1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        GenerateReport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        GenerateReport1.setText("Generate Report");
        GenerateReport1.setBorderPainted(false);
        GenerateReport1.setContentAreaFilled(false);
        GenerateReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReport1ActionPerformed(evt);
            }
        });
        Background.add(GenerateReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        GenerateReport2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        GenerateReport2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        GenerateReport2.setText("Add Train");
        GenerateReport2.setBorderPainted(false);
        GenerateReport2.setContentAreaFilled(false);
        GenerateReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReport2ActionPerformed(evt);
            }
        });
        Background.add(GenerateReport2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAccountActionPerformed
        // TODO add your handling code here:
        EditAccountAdminGUI E= new EditAccountAdminGUI(A.getUsername(),A.getPassword());
        dispose();
        E.setVisible(true);
    }//GEN-LAST:event_EditAccountActionPerformed

    private void AddTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTrainActionPerformed

    private void RemoveTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTrainActionPerformed
        // TODO add your handling code here:
        RemoveTrainGUI R= new RemoveTrainGUI();
        dispose();
        R.setVisible(true);
    }//GEN-LAST:event_RemoveTrainActionPerformed

    private void UpdateTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTrainActionPerformed
        // TODO add your handling code here:
        UpdateTrain U = new UpdateTrain();
        dispose();
        U.setVisible(true);
    }//GEN-LAST:event_UpdateTrainActionPerformed

    private void GenerateReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReport1ActionPerformed
        // TODO add your handling code here:
        GenerateReportUI G = new GenerateReportUI();
        dispose();
        G.setVisible(true);
    }//GEN-LAST:event_GenerateReport1ActionPerformed

    private void GenerateReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReport2ActionPerformed
        // TODO add your handling code here:
        AddTrainGUI A = new AddTrainGUI();
        dispose();
        A.setVisible(true);
    }//GEN-LAST:event_GenerateReport2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTrain;
    private javax.swing.JPanel Background;
    private javax.swing.JButton EditAccount;
    private javax.swing.JButton GenerateReport1;
    private javax.swing.JButton GenerateReport2;
    private javax.swing.JLabel Head;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RemoveTrain;
    private javax.swing.JButton UpdateTrain;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
