/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monorailbookingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author ahmed
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        areYou = new javax.swing.JLabel();
        passenger = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monorail Booking system");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("  Monorail Booking System");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        admin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/user.png"))); // NOI18N
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 180, 40));

        areYou.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        areYou.setForeground(new java.awt.Color(255, 255, 255));
        areYou.setText("You are:");
        getContentPane().add(areYou, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        passenger.setBackground(new java.awt.Color(255, 255, 255));
        passenger.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/passenger.png"))); // NOI18N
        passenger.setText(" Passenger");
        passenger.setToolTipText("");
        passenger.setMaximumSize(new java.awt.Dimension(50, 50));
        passenger.setMinimumSize(new java.awt.Dimension(10, 10));
        passenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerActionPerformed(evt);
            }
        });
        getContentPane().add(passenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 190, 40));

        jLabel1.setFont(new java.awt.Font("Noteworthy", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("The Capital in Minutes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/monrailSunset.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerActionPerformed
        // TODO add your handling code here:
        PassengerLoginUI p= new PassengerLoginUI();
        dispose();
        p.setVisible(true);
    }//GEN-LAST:event_passengerActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
      LoginAdminGUI L= new LoginAdminGUI();
      dispose();
      L.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JLabel areYou;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton passenger;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
