/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monorailbookingsystem;

/**
 *
 * @author ahmedsherif
 */
public class PassengerMenu extends javax.swing.JFrame {
    Passenger p= new Passenger();

    /**
     * Creates new form PassengerMenu
     */
    public PassengerMenu() {
        initComponents();
    }
     public PassengerMenu(Passenger p){
            initComponents();
            this.p= p;
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BookTicket = new javax.swing.JButton();
        UpdateBooking = new javax.swing.JButton();
        CancelBooking = new javax.swing.JButton();
        BookingInfo1 = new javax.swing.JLabel();
        AccountInfo = new javax.swing.JLabel();
        ManageYourAccount = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setText("Passenger Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        BookTicket.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        BookTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        BookTicket.setText("  Book Your Ticket");
        BookTicket.setBorderPainted(false);
        BookTicket.setContentAreaFilled(false);
        BookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTicketActionPerformed(evt);
            }
        });
        jPanel1.add(BookTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        UpdateBooking.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        UpdateBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        UpdateBooking.setText("  Update Booking");
        UpdateBooking.setBorderPainted(false);
        UpdateBooking.setContentAreaFilled(false);
        UpdateBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBookingActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        CancelBooking.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        CancelBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        CancelBooking.setText("  View Booking");
        CancelBooking.setActionCommand("Veiw Booking");
        CancelBooking.setBorderPainted(false);
        CancelBooking.setContentAreaFilled(false);
        CancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingActionPerformed(evt);
            }
        });
        jPanel1.add(CancelBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        BookingInfo1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        BookingInfo1.setText("- Booking Info ----");
        BookingInfo1.setToolTipText("");
        jPanel1.add(BookingInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        AccountInfo.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        AccountInfo.setText("- Account Info -----");
        jPanel1.add(AccountInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        ManageYourAccount.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        ManageYourAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/dot-right-arrow.png"))); // NOI18N
        ManageYourAccount.setText("  Manage Account");
        ManageYourAccount.setActionCommand("Manage Account");
        ManageYourAccount.setBorderPainted(false);
        ManageYourAccount.setContentAreaFilled(false);
        ManageYourAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageYourAccountActionPerformed(evt);
            }
        });
        jPanel1.add(ManageYourAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/monorail.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, 130));

        text.setFont(new java.awt.Font("Noteworthy", 0, 24)); // NOI18N
        text.setText("Monorail System");
        jPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBookingActionPerformed
        // TODO add your handling code here:
        updateBookingUI U=new updateBookingUI(p.getBooking());
        dispose();
        U.setVisible(true);
    }//GEN-LAST:event_UpdateBookingActionPerformed

    private void BookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTicketActionPerformed
        // TODO add your handling code here:
        TicketBookingUI B= new TicketBookingUI(p);
        dispose();
        B.setVisible(true);
        
    }//GEN-LAST:event_BookTicketActionPerformed

    private void CancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingActionPerformed
        // TODO add your handling code here:
        ViewBooking  V= new ViewBooking();
        dispose();
        setVisible(true);
    }//GEN-LAST:event_CancelBookingActionPerformed

    private void ManageYourAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageYourAccountActionPerformed
        // TODO add your handling code here:
        ManageAccountUI M =new ManageAccountUI(p);
        dispose();
        M.setVisible(true);
    }//GEN-LAST:event_ManageYourAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountInfo;
    private javax.swing.JButton BookTicket;
    private javax.swing.JLabel BookingInfo1;
    private javax.swing.JButton CancelBooking;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton ManageYourAccount;
    private javax.swing.JButton UpdateBooking;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
