/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monorailbookingsystem;

/**
 *
 * @author ahmedsherif
 */
public class UpdateTrain extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTrain
     */
    public UpdateTrain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateTrainHead = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        RunningTimeTextField = new javax.swing.JTextField();
        Route = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        RunningTime = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(null);

        UpdateTrainHead.setBackground(new java.awt.Color(0, 0, 0));
        UpdateTrainHead.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        UpdateTrainHead.setText("Update Train");
        getContentPane().add(UpdateTrainHead);
        UpdateTrainHead.setBounds(240, 30, 367, 64);

        ID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ID.setText("ID");
        getContentPane().add(ID);
        ID.setBounds(70, 170, 30, 29);
        getContentPane().add(RunningTimeTextField);
        RunningTimeTextField.setBounds(290, 300, 110, 30);

        Route.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Route.setText("Route");
        getContentPane().add(Route);
        Route.setBounds(70, 230, 71, 29);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "October Route", "New Capital Route" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 220, 200, 50);

        RunningTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RunningTime.setText("Running Time");
        getContentPane().add(RunningTime);
        RunningTime.setBounds(70, 300, 165, 29);
        getContentPane().add(IDTextField);
        IDTextField.setBounds(290, 160, 130, 30);

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(10, 10, 100, 31);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monorailbookingsystem/photos/monorail.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(620, 150, 128, 130);

        text.setFont(new java.awt.Font("Noteworthy", 0, 24)); // NOI18N
        text.setText("Monorail System");
        getContentPane().add(text);
        text.setBounds(610, 260, 178, 32);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(260, 260, 260))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        AdminMenu p= new AdminMenu();
        dispose();
        p.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String ID = jTextField1.getText();
//        String runningTime = jTextField2.getText();
//        String route = "";
//        if (jRadioButton1.isSelected()) {
//            route = "6 October";
//        } else if (jRadioButton2.isSelected()) {
//            route = "New Capital";
//        }
//        File file = new File("E:\\Trains.txt");
//        String data = "";
//        String old = "";
//        String newRecord = "";
//        String curr_run = "";
//        String curr_route = "";
//
//        try {
//            Scanner scanner = new Scanner(file);
//            while (scanner.hasNextLine()) {
//                data = scanner.nextLine();
//                if (data.substring(0, data.indexOf("#")).equals(ID)) {
//                    curr_run = data.substring(data.indexOf("#") + 1, data.indexOf(" "));
//                    String newString = ID + "#" + runningTime + "#" + route;
//                    break;
//                }
//                scanner.close();
//            }
//            while (scanner.hasNextLine()) {
//                data = scanner.nextLine();
//                if (data.substring(0, data.indexOf("#")).equals(ID)) {
//                    curr_run = data.substring(data.indexOf("#") + 1, data.indexOf(" "));
//                    String newString = ID + "#" + runningTime + "#" + route;
//                    try {
//                        BufferedReader reader = new BufferedReader(new FileReader(file));
//                        String line = reader.readLine();
//                        while (line != null) {
//                            old = old + line + System.lineSeparator();
//                            line = reader.readLine();
//                        }
//                        String newContent = old.replaceAll(ID + "#" + curr_run + "#" + curr_route, newString);
//                        FileWriter writer = new FileWriter(file);
//
//                        writer.write(newContent);
//                        reader.close();
//                        writer.close();
//                    } catch (FileNotFoundException ex) {
//                        Logger.getLogger(UpdateTrainGUI.class.getName()).log(Level.SEVERE, null, ex);
//                    } catch (IOException ex) {
//                        Logger.getLogger(UpdateTrainGUI.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
//            }
//            scanner.close();
//
//            newRecord = old.replaceAll(old, ID + "#" + runningTime + "#" + route);
//            FileWriter writer = new FileWriter(file, true);
//            BufferedWriter bw = new BufferedWriter(writer);
//            bw.write(newRecord);
//            bw.newLine();
//            bw.close();
//            writer.close();
//
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(UpdateTrainGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Route;
    private javax.swing.JLabel RunningTime;
    private javax.swing.JTextField RunningTimeTextField;
    private javax.swing.JLabel UpdateTrainHead;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
